apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-30ra
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0028-tenant/tkrw-pr714-0075-0028-app/devfile-sample-30ra@sha256:dd562661a7311fbcc054e6d2861342770067e42200e29748eb3ba38dba1a600a
        name: my-nodejs
        resources: {}
status: {}
