apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-30ra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-30ra
    app.kubernetes.io/part-of: tkrw-pr714-0075-0028-app
  name: devfile-sample-30ra
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-30ra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-30ra
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0028-tenant/tkrw-pr714-0075-0028-app/devfile-sample-30ra@sha256:dd562661a7311fbcc054e6d2861342770067e42200e29748eb3ba38dba1a600a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
